name: Deploy to Ubuntu VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      env:
        TOKEN: ${{ secrets.PROD_TOKEN }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /root/bot
          git pull
          echo "Starting slash commands update."
          node deploy-commands.js
          echo "Summoning pm2..."
          pm2 start main.js
          echo "Finished starting application main.js"